### PR TITLE
Upgrade pixi.js to v6.5

### PR DESCRIPTION
**Pull request by stevensnoeijen**
The current build on pixi-viewport does not work with v6.5.0 because of changes in the pixi's DisplayObject.

Issue for this PR: https://github.com/davidfig/pixi-viewport/issues/391

Changes:
- [feat: upgrade pixi.js to v6.5.1](https://github.com/davidfig/pixi-viewport/commit/69738a986bd8f40f3d0e431efd2b180f49cbba20)
- [chore: build](https://github.com/davidfig/pixi-viewport/commit/2baf6c1978ce71254b5e7bfbab034cbe41f9cd4b)

Please merge https://github.com/davidfig/pixi-viewport/pull/392 before merging this PR, this PR branch is extended from the electron fix.

### CODE REVIEW

**Comment by kurtwaldowski-echelon** [comment]
The formatting changes make this merge seem much larger than it is

**Comment by stevensnoeijen** [comment]
Good point, I'll check this tomorroe

**Comment by stevensnoeijen** [comment]
> The formatting changes make this merge seem much larger than it is

Good point I'll check this tomorrow

**Comment by kurtwaldowski-echelon** [comment]
> > The formatting changes make this merge seem much larger than it is
> 
> The formatting you mean is on the `dist` folder which is generated though `yarn build` and can be ignored, because I did not directly changed that. I did just run `build` this so that I can use these changes in the meanwhile. When @davidfig creates a new release he probably run this again himself.

Derp good point! Thanks!

**Comment by stevensnoeijen** [comment]
bump @davidfig

**Comment by davidfig** [comment]
Thanks!

**Pull request merged**
