### PR TITLE
Pixiv7

### LINKED ISSUE #404: pixi.js@7 support
v7 of pixi is out (woo!) - any plans/timeline on supporting it? InteractionManager seems to be the only potential issue for this library, though from what I read, it's a drop-in replacement so might just be a case of allowing `^7.0.0` for peer dependencies?

### PR DESCRIPTION
**Pull request by cuire**
Closes #404 

### What was done:
- Events typing using `GlobalMixins` 
- Switched to `FederatedEvent API`
- Switched type of `interaction` prop to `EventSystem` (we can change name to, but I left it same for backward compatibility. 
- Renamed `'{pluginName}-removed'` event to `'plugin-removed'` and added `pluginNamed` payload, to type it correctly. 
- Renamed `whell` event to `wheel-start`, to prevent collisions with pixi's wheel event. 
- Removed `{dx, dy, dz}` from `wheel-start`, since it already in `event`

### Not related to v7
- Added `dist/` to gitignore, as part of #408

### CODE REVIEW

**Review by sfwhite — COMMENTED** [review]
I'm certainly not an expert in this library or PixiJS for that matter, but I've spot checked a number of files against the Pixi change notes and this PR looks to be in order.

**Comment by cuire** [comment]
After a while I think that we need to rename `interaction` field, since it not backward compatible. 😵‍💫

**Comment by sfwhite** [comment]
Yeah looks like pixi dropped that plugin entirely in favor of the EventSystem as a member named `events`. Should probably adjust to match, and apply a deprecation like they did.

[@pixijs/core v7 - PluginSystem.ts#L66](https://github.com/pixijs/pixijs/blob/7326aa5be3858d438ed6995d4207af0b4f8ad055/packages/core/src/plugin/PluginSystem.ts#L66)

**Comment by oyed** [comment]
@davidfig Thanks for merging! Can you publish a new NPM version please?

**Comment by oyed** [comment]
Alright, thanks guys - looking forward to updating all of my pixi dependencies!

**Comment by pachyderme** [comment]
Hello @davidfig, first, thank you for your excellent work! I plan to use your package for my project in pixijs v7.
Do you have any news about the compatibility with v7? A date? Do you need any help?

**Pull request merged**
