### PR TITLE
In type definitions: change string to (string & {}) when in union with literals

### PR DESCRIPTION
**Pull request by sransara**
Per discussion on https://github.com/davidfig/pixi-viewport/pull/234

[Typescript playground link](https://www.typescriptlang.org/play?#code/PTAEGEEMGcFNQIwC5QBED2tqgHboC6jQAW6A7qPsfOgA74CW6O2DOob+sANtw3C1gAofAE9a8AGqwA5gyygAvKADktAK4BbWgGs2K0AB9VAY3VnNAI1gAnA8ej4bbGUO6xCAN2ShpchcrAAFRoPB7wVPA2WISQOAAmoLTR0Ngm+NwA1NC0kCbwQWAqZhbWdm4eoJ4ATCh+8tjKKgBe5ibEbAwqQkIgEDDwtaAAyqRk2JGgdIzMrOycPHwCcCLi8ABiNuoM+I2qkLS07tD2qug2cTJYpwAUjs44MqAAZKAA3gC+AJQVhABmPk2212SlAwVC7i4lGooBSsQSSRSaQy2Vy+VAhX2h2O3UhoD+QyBOz2Khk6kgnkgBj6VH4lDWoHasBMOgm6HQQA) for testing

### CODE REVIEW

**Comment by davidfig** [comment]
published as 4.11.3

**Comment by luchidalgo** [comment]
Yes it's better in this thread 👍
I've just create a fresh new ts project and add following line : 
`import { Viewport } from 'pixi-viewport';`

I immediatly have the following error:

`ERROR in node_modules/pixi-viewport/@types/index.d.ts:71:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'underflow' must be of type 'string', but here has type 'UnderflowType'.

71     underflow?: UnderflowType`

**Comment by davidfig** [comment]
Is underflowType used in pixi-viewport as well? Not sure I understand the conflict.

**Comment by mcdenhoed** [comment]
I am also getting the errors that @luchidalgo mentions. I think the cause of it is pretty simple. There's two declarations of DragOptions being made in the pixi-viewport types file.

Here:
https://github.com/davidfig/pixi-viewport/blob/master/%40types/index.d.ts#L34-L46

and here:
https://github.com/davidfig/pixi-viewport/blob/master/%40types/index.d.ts#L65-L75

The first one declares `underflow` to be a generic `string`. The second one defines it to be the constrained `UnderflowType` type that @sransara fixed in this MR, but this type isn't compatible with the already-declared wider `string` type for `underflow`.

In #242 I remove the second definition of the `DragOptions` interface (which I assume was defined by mistake) and edit the first one to have `underflow` be of type `UnderflowType` instead of `string`. That seems to fix the issue for me.

**Comment by sransara** [comment]
@mcdenhoed Thanks for looking in to it. I didn't get much time lately. Looks like you have found the real cause of the error :+1:

For your question @davidfig: not sure if there's a conflict, but here's the duplicate definition I noticed across the two repos.
`UnderflowType` definition in pixi-viewport: https://github.com/davidfig/pixi-viewport/blob/master/@types/index.d.ts#L4
And `UnderflowType` definition in pixi-scrollbox: https://github.com/davidfig/pixi-scrollbox/blob/master/@types/index.d.ts#L5

**Pull request merged**
