### PR TITLE
Feature custom world bounds

### PR DESCRIPTION
**Pull request by ambientlight**
Related Issue: https://github.com/davidfig/pixi-viewport/issues/159

Pardon for taking so long here, totally went out of my head. Let me know if any help or more updates needed, thanks!

### CODE REVIEW

**Comment by davidfig** [comment]
Sorry it's taken me so long to review this. Are there other uses besides allowing the bounce plugin to have padding/different size? 

Hard coding the boundsBottomRight in the viewport constructor is worrisome because the viewport also supports undefined _worldWidth and _worldHeight (in that case it relies on viewport.width/viewport.height). 

If it's just for bounce, it would be better to include a padding or fixed size world bounds within the bounce plugin and use that in concert with oob to get the proper size for the bounce. If it's needed for other plugins or the viewport in general, then we should probably rethink how it works and make it adjustable when _worldWidth changes.

**Comment by ambientlight** [comment]
> Sorry it's taken me so long to review this. Are there other uses besides allowing the bounce plugin to have padding/different size?

No worries, for now my only use case if having the bouncing off the custom bounds.
I couldn't go with the existing implementation just because the left corner was rooted in (0,0)

> If it's needed for other plugins or the viewport in general, then we should probably rethink how it works and make it adjustable when _worldWidth changes.

What do you think if we make `boundsBottomRight` as a computed property getter on `worldWidth`/`worldHeight`, but in this case it feels it might confusing when `boundsTopLeft` can be set but `boundsBottomRight` is readonly. I also not sure how good is an idea when setting `boundsBottomRight` would also update the `_worldWidth`/`_worldHeight`

**Comment by davidfig** [comment]
Checkout out v4.4.0. Instead of changing the viewport, I added bounce.options.bounceBox, which allows you to set custom bounds for the bounce. For your use, you just need to set bounceBox to {x: -startX, y: -startY } and it should work properly with the calculated worldWidth and worldHeight.

Let me know if that helps.

**Comment by ambientlight** [comment]
@davidfig: wow great, thanks, will test that out and close this then, Thanks!

**Pull request closed without merging**
