### PR TITLE
Drag, snap, and pinch improvements

### PR DESCRIPTION
**Pull request by qwertysam**
NOTE: *README.md* must be updated with the new docs (I still can't seem to get that markdown-api command to output anything to the file)

### CODE REVIEW

**Comment by davidfig** [comment]
Nice changes. Testing and working through some fixes before I merge.

**Comment by davidfig** [comment]
I made some minor changes and a major change in snap. The new snap options confused me, so I decided to simplify them and add robust event handling. I think you'll still be able to accomplish the use cases by relying on the events. Take a look and let me know what you think.

**Comment by davidfig** [comment]
Also note that I moved the zoom clamping (in pinch and wheel) to the clamp-zoom plugin. It removed the duplicate code and made the demo easier to write.

**Comment by qwertysam** [comment]
Thanks for the review! I'll check out the new features

**Pull request merged**
