### PR TITLE
fix window references during SSR

### LINKED ISSUE #432: Viewport causes server-side builds to fail
pixi-viewport uses window at the module level, which makes it crash any build that uses server side rendering, for example Next and Gatsby. These frameworks build the app on the server with node, which has no window object. The build will fail with any import from the pixi-viewport, even if no viewport is created.

luckily, this is a pretty straightforward fix though, just need to check the type of window before using it like so:
`typeof window === "undefined" ? 0 : window.innerWidth`

this person ran into the same issue, but closed it: #398

### PR DESCRIPTION
**Pull request by RJWadley**
fixes #432

### CODE REVIEW

**Comment by milkyskies** [comment]
Thank you! I hope this gets merged.

**Comment by ahmafi** [comment]
I have tried this on a `next.js` project, but I'll get `Cannot read properties of undefined (reading 'shared')`.

I'm using it like this in a `useEffect` hook:
```js

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const app = new PIXI.Application({ width: 500, height: 400 });
    containerRef.current.appendChild(app.view);

    // create viewport
    const viewport = new Viewport({
      screenWidth: window.innerWidth,
      screenHeight: window.innerHeight,
      worldWidth: 1000,
      worldHeight: 1000,

      events: app.renderer.events, // the interaction module is important for wheel to work properly when renderer.view is placed or scaled
    });

    // add the viewport to the stage
    app.stage.addChild(viewport);

    // activate plugins
    viewport.drag().pinch().wheel().decelerate();

    // add a red box
    const sprite = viewport.addChild(new PIXI.Sprite(PIXI.Texture.WHITE));
    sprite.tint = 0xff0000;
    sprite.width = sprite.height = 100;
    sprite.position.set(100, 100);
  }, []);

```

Am I missing something?

**Comment by RJWadley** [comment]
@ahmafi I believe the latest version of pixi-viewport uses pixi.js v7, and it looks like you're using pixi.js v6. Could you try it with 7?

**Comment by VasiliKubarka** [comment]
@RJWadley I suppose merging will go faster if you will clean up `yarn.lock` changes

**Comment by rbozan** [comment]
can confirm it works

**Comment by artokun** [comment]
bump

**Comment by artokun** [comment]
@RJWadley you should rebase + fix your yarn.lock diff

**Comment by himrocks33** [comment]
Merge please!

**Comment by Dayonel** [comment]
Bump

**Comment by pietrovismara** [comment]
Was this released on NPM? I'm on v5.0.2 and I still get errors from the window references.

**Comment by RJWadley** [comment]
yeah, looks like this was never published. I think the library would probably benefit a lot from an auto-publish action on push to main.

@davidfig I understand you might be a bit busy, would you like help maintaining pixi-viewport?

**Comment by h-a-s-k** [comment]
viewport
Still a problem

**Pull request merged**
