### PR TITLE
babel transforms to es2015 before publish

### PR DESCRIPTION
**Pull request by hassanshaikley**
Let me know if this is missing anything! I don't mind doing the same thing for your other PIXI libraries!

### CODE REVIEW

**Comment by hassanshaikley** [comment]
Woops. The budo test server is being wonky!

**Comment by hassanshaikley** [comment]
There ya go : )

**Comment by davidfig** [comment]
Hassan, good work! I'm currently in the process of converting pixi-viewport to use more pixi functionality (e.g., PIXI.ticker.shared and PIXI.Interactive). The code is in the pixi-more branch. This change has the advantage of not relying on yy-loop and yy-input, both of which are written in es6. 

I'd rather wait to babelify pixi-viewport until that pixi-more moves to master since it will require less work to re-babelify the dependencies that I probably won't support anymore.

If you still want to help, a good place to start the conversion is pixi-ease. (Sorry for the churn!)

A couple of suggestions for your changes:

* use babel-cli instead of babel
* use babel-preset-env instead of the es2015
* the demo should use the /dist files since that's what npm users use

**Comment by hassanshaikley** [comment]
I have been meaning to check out that branch and give you feedback! It sounds like the PIXI thing to do.

I don't mind a wait, take your time. Let me know what you think about this PR and if it looks good to do you I will go ahead and do the same with pixi-ease!

**Pull request closed without merging**
