### PR TITLE
✨✨✨ V5 ✨✨✨

### LINKED ISSUE #426: Master lagging (npm) release
The master branch is more recent than the latest release. This may be confusing, as for example people depend on pixi7+ but get pixi6+ in the package.

### PR DESCRIPTION
**Pull request by cuire**
Closes #426, #408 , #352, #378, #425. 

Finally ready to merge PR. 

That PR includes everything from #421. And adds more:
- Flems demo is updated. 
- Remove peerDependencies https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#-abandon-the-use-of-peerdependencies
- Everything from #418, moved here, due to next feature

# Installable via git now

While PR is no merged, you can use these to continue working on projects.

### npm 
```bash
npm i cuire/pixi-viewport#v5
```
### yarn v2+ berry
yarn classic doesnt have life cycle scripts (or I dont found them 😵‍💫). So for now it only yarn 2. https://github.com/yarnpkg/yarn/pull/6131
```bash
yarn add pixi-viewport@cuire/pixi-viewport#v5
```

### pnpm
```bash
pnpm add cuire/pixi-viewport#v5
```

### CODE REVIEW

**Comment by olegarino** [comment]
This is really appreciated thank you sir.

**Comment by ioveracker** [comment]
> While PR is no merged, you can use these to continue working on projects.

Installing via your fork doesn't work out of the box because the `pixi-viewport` code in my app's `node_modules` doesn't get bundled into the `dist` directory.

```
ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "pixi-viewport". The package may have incorrect main/module/exports specified in its package.json.
Failed to resolve entry for package "pixi-viewport". The package may have incorrect main/module/exports specified in its package.json.
```

I was unable to build it manually inside of my app's node_modules.

Is there a good way to test this from your fork?

**Comment by TimWillebrands** [comment]
I'm not sure if this PR is the cause, but when using this branch we're running into this issue with dragging: https://github.com/davidfig/pixi-viewport/issues/422#issuecomment-1429535913

**Comment by Disorrder** [comment]
can't use this version because of events:
```
import { EventSystem } from "@pixi/events";

  const viewport = new Viewport({
    ticker: app.ticker,
    events: new EventSystem(app.renderer),
  });
```
image

**Comment by davidfig** [comment]
Thanks @cuire! Published as v5 on npm.

**Pull request merged**
