### PR TITLE
calculate point relative to divWheel

### PR DESCRIPTION
**Pull request by mrBuchmann**
To allow proper zooming to pointer behavior when using divWheel != document.body, calculate relative pointer position to divWheel.

Since layerX/layerY (https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/layerX) are non-standard, calculate position as suggested by https://stackoverflow.com/a/10816667/1187951

### CODE REVIEW

**Comment by mrBuchmann** [comment]
There is still an issue with the worlds position when zooming in this pull request.
Applies if the divs position on the screen changes after scrolling.
I'm trying to fix this in the next couple of days

**Comment by davidfig** [comment]
See issue #45. I think there's a bug with divWheel even before your pull request.

**Comment by mrBuchmann** [comment]
Sorry for the delay. Using mapPositionToPoint, as suggested by David, works much better.

**Comment by davidfig** [comment]
Awesome! Looks great. I fixed some formatting and added a bug fix for wheel calls when wheel() is not active. Thanks for your help!

**Pull request merged**
