### PR TITLE
Fix endless snap zoom

### PR DESCRIPTION
**Pull request by kaflake**
Actualy this.parent.moveCenter is called on every update cyle while snapping.
this results to call reset() in the plugin -> snapping is set to null and starts again

### CODE REVIEW

**Comment by kaflake** [comment]
Need the position, else there is a directly position jump at the end.

**Comment by kaflake** [comment]
Remove reset() from snap-zoom plugin. That is the same way like in the snap plugin, which also dont support reset.

**Comment by davidfig** [comment]
I think I made this change already when I fixed issue #174. Please check the latest version (I updated npm, but I forgot to git push). Please see if the current version resolves this bug. Thanks!

**Comment by kaflake** [comment]
Its working perfectly, thanks a lot for your great work. I just looked at the git and dont looked in npm for an update.

**Pull request closed without merging**
