### PR TITLE
v5 fixes

### LINKED ISSUE #352: mjs build?
First let me say nice work with this project, I use and like it a lot!

In a recent project of mine I started using the pixi.js mjs build for the browser, it kinda allows me to slimline my own build process. 
Are there any plans add the same for viewport?

### PR DESCRIPTION
**Pull request by cuire**
I switched build tool to `vite`. As a result npm package has become much lighter  lighter from 1.67mb to 0.15mb. I also decided to finally add an eslint precommit hook and `.gitattributes` to normalize eol.
Closes #352  
I have removed unused dependencies in package.json, because why not.
And in order to exclude troubles with build in the future, I added CI script. 
It remains only to update `flems` demo. I'm having trouble with this part.

### CODE REVIEW

**Comment by cuire** [comment]
I tested new build with standalone, js and ts. GlobalMixins works as well. 
Here is umd test [codepen](https://codepen.io/cuire/pen/NWBdZYa).
But I'm still waiting for the review.

**Comment by oyed** [comment]
@cuire I'm trying to use your branch locally via `"pixi-viewport": "github:cuire/pixi-viewport#v5",`, but I think you forgot to change a filename here: https://github.com/cuire/pixi-viewport/blob/v5/scripts/copy.js#L4

Seems like it should be an `_` instead of a `-` in the filenames

**Comment by cuire** [comment]
Hey @olegario. We're all waiting for @davidfig to review this branch. It will be cool, if you can upgrade the 'flems' demo to pixiv7. This does not go well with memotypes from cdn or something simular. It was more that month ago 😵‍💫. Tbh, I didn't remember.
I am also blocked with this. Im think it's time to close this pr, complete update and publish fork to npm. Or even better, I can make it installable via git. Like [so](https://stackoverflow.com/questions/49992677/how-to-install-specific-branch-of-git-repository-using-yarn). 
Then I'll open new pr with all in one place and ready to merge.

**Comment by cuire** [comment]
Here're all the tasks: https://github.com/cuire/pixi-viewport/issues?q=is%3Aissue+is%3Aopen
I'll start working on it when I have a bit more time, but I think it should be easy.

**Pull request closed without merging**
