### PR TITLE
Added fit plugin

### PR DESCRIPTION
**Pull request by qwertysam**
The fit() function is now used to invoke the fit plugin.
Original functions fitHeight() and fitWidth() retain their original functionality.
Original fit() function is now fitWorld()

### CODE REVIEW

**Comment by davidfig** [comment]
This looks like a snap-zoom plugin. Is that a better name for what it does? 

Maybe replace directions/value with: width or minWidth/maxWidth, and height or minHeight/maxHeight. That should provide more flexibility. 

options.center should probably be a PIXI.Point and then use either the point or the current center when animating. 

It probably also needs the snap.options.interrupt flag.

**Comment by davidfig** [comment]
Also, have you looked at the demo in the docs/ directory? It's a bit confusing, but if you can set up the wiring, it's a great way to test options for plugins.

Here's how to get it running locally:

yarn global add budo 
(or npm i budo -g)
yarn test
(or npm run test)

**Comment by qwertysam** [comment]
I pushed the reccommended changes, seems to be working well!

**Comment by davidfig** [comment]
Great work! 

I moved the width/height to options since in most cases one of them will be undefined to avoid squashing. Otherwise just two minor fixes: end event triggered too often, and center updated even when not animating.

**Pull request merged**
